version : "3"
services : 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - ./postgres/dbdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"      
    restart: always

  # nginxcont:
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - flaskservice1
  #     - flaskservice2
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  flaskservice1:
    build: ./Flask_Blog
    ports:
      - 5001:5000
    volumes:
      - ./Flask_Blog:/Flask_Blog
    depends_on:
      - db
    entrypoint: /Flask_Blog/docker-entrypoint.sh
    restart: always

  flaskservice2:
    build: ./Flask_Blog
    ports:
      - 5002:5000
    volumes:
      - ./Flask_Blog:/Flask_Blog
    depends_on:
      - db
    entrypoint: /Flask_Blog/docker-entrypoint.sh
    restart: always