"""empty message

Revision ID: 15313da2a5ca
Revises: 4ec27d6b1057
Create Date: 2021-05-13 09:33:03.467029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15313da2a5ca'
down_revision = '4ec27d6b1057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_temp_name_key', 'users', type_='unique')
    op.drop_column('users', 'temp_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_temp_name_key', 'users', ['temp_name'])
    # ### end Alembic commands ###
