"""empty message

Revision ID: 7e531513af2b
Revises: 849430eff562
Create Date: 2021-06-26 11:16:21.027324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e531513af2b'
down_revision = '849430eff562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content2', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
