"""empty message

Revision ID: 849430eff562
Revises: 10fcc538e5c9
Create Date: 2021-06-26 11:12:50.750992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849430eff562'
down_revision = '10fcc538e5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content2', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content2')
    # ### end Alembic commands ###
